Makefile
client/binding_test.go
client/client_test.go
client/invoke_test.go
client/pubsub_test.go
client/secret_test.go
client/state_test.go

Cleaned up tests and added test coverage in make for the `client` package

test init, test coverage

---

client/client.go

Addresses the concern (##33) that users would create many instances of the client when using the default constructor (potentially expensive operation) by ensuring that the client.NewClient() factory method runs the client creation code only once per lifecycle and returns previously created instance for all subsequent invocation.

adds only once for default client constructor

---

example/client/main.go

Better etag default to avoid error related to errors from Dapr HTTP API on a non-integer value (https://github.com/dapr/dapr/issues/1869)

non-integer etag value in example

---

example/serving/grpc/main.go
example/serving/http/main.go

Nice (consistent across HTTP and gRPC) formatting for the example log entries
JSON Content 
```shell
Event - PubsubName:messages, Topic:topic1, ID:3fec7421-d947-41cf-ac9c-3b614b316358, Data: {"to":"Lary","message":"hi","from":"John"}
```
XML Content 
```shell
Event - PubsubName:messages, Topic:topic1, ID:1f40a77c-8091-4267-bd5f-ff7bc1835ff8, Data: <message><from>John</from><to>Lary</to></message>
```
BIN Content
```shell
Event - PubsubName:messages, Topic:topic1, ID:179f4711-95d6-4558-b6f7-3422f35b4e10, Data: 0x18, 0x2d, 0x44, 0x54, 0xfb, 0x21, 0x09, 0x40
```

cleans up log entry in examples

---

example/Readme.md
example/pubsub/README.md

Use `dapr-http-port` and `dapr-grpc-port` instead of `port`

[doc] Use the latest options for port

---

.github/workflows/release-on-tag.yaml

https://nvd.nist.gov/vuln/detail/CVE-2020-15228 advises that `set-env` and `add-path` are not secure, so they will be disabled very shortly on workflows. This changes `set-env` to the recommended upgrade.

Remove set-env usage

---

.github/workflows/test-on-push.yaml

To pick up fix for CVE-2020-15228

Switch to golangci/golangci-lint-action@v2.2.1

---

service/grpc/binding_test.go
service/grpc/invoke_test.go
service/grpc/service_test.go
service/grpc/topic_test.go

adds grpc serving error tests

---

client/client.go
client/state.go
client/state_test.go
example/client/main.go

- rename SaveStateItems() to SaveBulkState(); 
- rename GetStateItems() to GetBulkState();
As discussed in this Issue:
https://github.com/dapr/dapr/issues/2368

rename SaveStateItems() and GetStateItems()

---

.github/workflows/release-on-tag.yaml

Adds go sdk channel notification in Dapr discord server on successful release (on tag completed w/o errors)

discord notif on release

---

client/state.go

In state get method, the metadata in response is missing.  
Just add it, and set the value from result.

add metadata in state get response

---

service/http/invoke.go

All headers should be added before w.WriteHeader(status code)

fix service invoke handler always return text/plain content type

---

client/pubsub.go

#161 set `application/json` DataContentType for `PublishEventfromCustomContent`

fix PublishEventfromCustomContent missing DataContentType

---

Readme.md
client/client.go
client/state.go

When we use go-sdk's GetState, we don't know consistency default rules.
i use GetState method it running ok in redis test environment, but i publish server to production environment , redis configuration permissions reduced to cause bellow failed. This is a fatal problem.
```shell
(error) ERR unkown command 'WAIT' or wrong number of arguments
```

feat(state): SaveState expose StateOptions

---

client/invoke.go
service/grpc/invoke.go

On both client and server, this does not call `errors.Wrap` on errors, so the original gRPC error object (with status code and message) is preserved.
Fixes #186

Do not wrap errors for invocations

---

examples/service/Makefile
examples/service/README.md
examples/service/custom-grpc-client/main.go

The approach is documented to deal with 4MB gRPC limit on client side with DAPR client.
https://github.com/dapr/go-sdk/issues/189
1. Example `examples/service/custom-grpc-client/main.go` have been added working demo.
2. The README is updated at this location `examples/service/README.md`
3. Entry in Makefile to run the example.

Add documentation and example to deal with gRPC 4mb limit

---

service/http/service.go
service/http/service_test.go

This addresses https://github.com/dapr/go-sdk/issues/208. It implements the `Stop` method on the HTTP service which is currently a [no-op with a `TODO` comment](https://github.com/dapr/go-sdk/blob/main/service/http/service.go#L49).
It sets a 5 second timeout for the shutdown process. Open to suggestions to avoid the `time.Sleep` in the tests or for a more appropriate shutdown timeout. Thanks for taking a look!

Implement HTTP service stop with a 5 sec timeout

---

actor/state/state_async_provider.go
actor/state/state_async_provider_test.go

When there is only readonly state operations (Get, for example), after invoking methods, the state save will error with "actor save state transactionally invocation request param operations is empty" and returns to the user with following error message:
```
rpc error: code = Internal desc = error invoke actor method: rpc error: code = Internal desc = error invoke actor method: error from actor service:
```

Fix error saving actor state for readonly changes

---

go.mod
go.sum

Upgrade dapr to v1.6.0 for it is already published.
ref: https://github.com/dapr/go-sdk/issues/245

upgrade dapr to v1.6.0

---

service/common/service.go
service/grpc/service.go
service/http/service.go

It is essential to gracefully shutdown the server in order to handle the `SIGTERM` signal.
I was planning to add tests. Please provide feedback on this PR.
Thank you.

[WIP] Implement graceful shutdown

---

service/common/type.go
service/grpc/topic.go
service/grpc/topic_test.go
service/internal/topicregistrar.go

As the Go-SDK is special in that it opens a gRPC server to subscribe for events, it isn't currently possible to allow for wildcard topics because of the existing `pubsub + topic` validation.
This PR adds the ability to optionally skip topic name validation for a given pub/sub.
Unblocks https://github.com/dapr/dapr/issues/4461.
cc @thielepaul

Add option to disable topic validation

---

client/client.go
client/client_test.go

Signed-off-by: Paul Thiele <thielepaul@gmail.com>
Expose GrpcClient so that APIs currently not supported by the SDK (e.g. configuration) can be used with the sdk.
Close #188

Expose base grpcclient over client interface

---

.github/workflows/fossa.yml

Signed-off-by: Shubham Sharma <shubhash@microsoft.com>
1. Due to a recent regression in FOSSA action's main branch, we are moving to the last working version.
1. Update the trigger branches for the FOSSA workflow.
Related to: https://github.com/dapr/dapr/issues/4523

Update fossa workflow's action version and trigger branches

---

.github/workflows/fossa.yml

Signed-off-by: Shubham Sharma <shubhash@microsoft.com>
If FOSSA workflows run on forks, it creates a new project on FOSSA. The workflow was introduced in https://github.com/dapr/go-sdk/pull/266

FOSSA workflow should not run on forks

---

client/client.go

Started playing around with dapr and had a slight issue as I followed the docs on the main website which suggested running dapr with: `dapr run --app-id myapp --dapr-http-port 3500`. 
When it came to creating the client I assumed I could use `dapr.NewClientWithPort("3500")` but upon further investigation I saw it's internally using a gRPC port. I think we should make it a bit clearer to the reader.

chore(client): update func definition to be clearer

---

Readme.md
client/client.go
client/client_test.go

Fix for https://github.com/dapr/go-sdk/issues/259
The default timeout is too short and may cause the main container to restart when the sidecar is starting slowly.

fix: client default timeout

---

actor/manager/manager.go

I was debugging a panic in a local application I was developing and noticed this issue. A validation failure isn't correctly handled as a failure, and we insert a nil value into the map. This value in this map is later dereferenced, resulting in the following panic:
```
http: panic serving 127.0.0.1:45598: runtime error: invalid memory address or nil pointer dereference
goroutine 248 [running]:
net/http.(*conn).serve.func1()
/home/linuxbrew/.linuxbrew/Cellar/go/1.19.1/libexec/src/net/http/server.go:1850 +0xbf
panic({0x9558a0, 0xe4d7c0})
/home/linuxbrew/.linuxbrew/Cellar/go/1.19.1/libexec/src/runtime/panic.go:890 +0x262
github.com/dapr/go-sdk/actor/manager.(*DefaultActorContainer).Invoke(0xc0000be810, {0xc000048126?, 0x9?}, {0xc0003fc000, 0x4, 0x200}) …
```

Fix panic in actor server when invalid methods encountered

---

client/client.go
client/state.go
client/state_test.go

In the state API there's an existing DeleteStateWithETag() convenience
function but there does not appear to be an equivalent
SaveStateWithETag(). This commit adds SetStateWithETag() so that
consumers of the SDK don't have to employ the more verbose
SaveBulkState() when they only need to update a singular item.
Client code updating a single item with an etag prior to this commit
looks like:
```
item := &dapr.SetStateItem{
Etag: &dapr.ETag{
Value: "deadbeef",
},
Key:   "order_1",
Value: []byte(data),
}
err := client.SaveBulkState(ctx, store, item)
```
Client code after this commit can reduce to:
```
err := client.SaveStateWithEtag(ctx, store, "order_1", []byte(data), "deadbeef")
```
Signed-off-by: Mike Brown <github@torvosoft.com>

Add SaveStateWithETag() convenience function

---

client/client.go
client/client_test.go
client/wait.go
client/wait_test.go

App might depend on sidecar right away. This PR adds a Wait() method to
enable app to wait for sidecar to be up before invoking the first call.
GRPC client creation on Dapr Go SDK is blocking, so waiting for client
readiness  is less of a problem here than on SDKs where client
connection establishment is async.
Closes #287

Add wait() method to block until Sidecar is up.

---

Readme.md

Signed-off-by: Samantha Coyle <sam@samcoyle.me>
Update Dapr CLI installation link in readme, among other very very minor changes regarding spacing and periods.
This resolves issue [#353](https://github.com/dapr/go-sdk/issues/353).

docs: fix link and add periods/spacing

---

service/grpc/service.go

Currently the gRPC server is created within the `newService` call which does not support passing gRPC server options. This change adds an additional "optional" 
parameter that is the gRPC server options that will be passed to the grpc server ctor.
Signed-off-by: Joni Collinge <jonathancollinge@live.com>

Allow gRPC options on gRPC server

---

go.mod
go.sum
service/http/service.go
service/http/topic.go

Description:
Switch from Gorilla Mux to Chi as Gorilla Mux is no longer maintained.
The APIs remained fairly similar.
Link to tracking Issue:
[#344 ]
Testing:
Regression test are passed.
Documentation:
N/A

[service/http]switch from Gorilla Mux to Chi

---

client/client.go
client/client_test.go
client/pubsub.go
client/pubsub_test.go
client/utils.go
client/utils_test.go
daprdocs/content/en/go-sdk-docs/go-client/_index.md
examples/pubsub/README.md
examples/pubsub/go.mod
examples/pubsub/go.sum
examples/pubsub/pub/pub.go
examples/pubsub/sub/sub.go

This PR adds bulk publish support to the Go-SDK.
Adds the following signature to client.
```go
// PublishEvents publishes multiple events onto topic in specific pubsub component.
// If all events are successfully published, response Error will be nil.
// The FailedEvents field will contain all events that failed to publish.
PublishEvents(ctx context.Context, pubsubName, topicName string, events []interface{}, opts ...PublishEventsOption) PublishEventsResponse
```
Partially addresses #325

Add support for bulk publish

---

daprdocs/content/en/go-sdk-docs/go-client/_index.md

Related docs issue: dapr/docs#2770
Needs review:
Need example:

[docs] Add missing client examples

---

service/grpc/service.go
service/grpc/service_test.go

We are building an application that exposes it's own gRPC service, it also needs to subscribe to the dapr pub/sub component.
Currently we are allowed to set the listener, but this is not enough, as we found that about half of the time, our own gRPC server responds, and the other half of the time the dapr service responds with an `unknown service xxx.xxx`.
If this is merged, the user is allowed to set their own grpcServer with the `NewServiceWithGrpcServer()` func.
In action:
```golang
lis, _ := net.Listen("tcp", "localhost:8080")
server := grpc.NewServer()
// Register dapr
dapr.NewServiceWithGrpcServer(lis, server)
// Setup dapr subscriptions here
// Register own services
proto.RegisterOwnServer1(server, ownServer1{})
proto.RegisterOwnServer2(server, ownServer2{})
go server.Serve(lis)
``` …

Allow setting own gRPC server when calling `NewService`

---

actor/actor.go
examples/actor/serving/main.go

Due to the nature of the current implementation of write through caching of actor state and the unavailability of the real TTL expire time of state keys, SDKs will have an inconsistent view of the world when it has a cold cache and the state store has TTL keys. The TTL functionality has been put behind a feature gate in daprd. See [dapr/dapr](https://github.com/dapr/dapr/pull/6400) for more details.
PR updates the SDK comments to reflect this.]
/cc @artursouza @yaron2

Add note about Actor State `WithTTL` being feature preview.

---

daprdocs/content/en/go-sdk-docs/go-client/_index.md

Add `encrypt` and `decrypt` examples to the go client doc
Remove empty headers that still need examples someday :)

[docs] Add cryptography examples

---

service/http/binding.go
service/http/invoke.go
service/http/topic.go
service/http/topic_test.go

The HTTP service in multiple places expected a Content-Length header or it would refuse to parse the body.
This breaks streaming (see [test failures](https://github.com/dapr/dapr/actions/runs/5446419269/jobs/9907127023)), since in case the data is streamed it's not possible to know the content's byte length in advance. The Content-Length header is not required per the HTTP specs, so we should not enforce its presence.
This fixes the issue by not relying on the Content-Length header's presence.

Fixed: do not require a Content-Length header

---

daprdocs/content/en/go-sdk-docs/go-client/_index.md

Accidentally removed bulk publish from client doc earlier, adding it back

[docs] Add bulk publish example back

---

actor/manager/manager.go
client/actor.go

Issue where the serializer isn't used and json is specified to marshal/unmarshal parms
Merging this will close #317
Signed-off-by: mikeee <hey@mike.ee>

fix actor serialization

---

.github/workflows/test-on-push.yaml
.github/workflows/validate_examples.yaml
Makefile

Addresses https://github.com/dapr/go-sdk/issues/450 
Added job to ccheck for if the go mod needs updating when we create pull requests

Enhance workFlow to add go mod tidy

---

examples/hello-world/README.md
examples/socket/README.md

Replace the dapr getting-started link with two steps to install the cli and initialise dapr locally.

fix: fix broken dapr setup links

---

Makefile
client/client.go
client/client_test.go
client/metadata.go
go.mod
go.sum

This is needed in components-contrib as we cannot pin an updated runtime in cert tests without an updated Go SDK, due to a complex circular dependency

Updates pinned runtime

---

client/client.go

Explicitly noting a deprecated function to make it more obvious to end users. Suggestions to wording it differently are welcomed.

add note on unsubscribeConfiguration being deprecated

---

client/client.go
client/internal/parse.go
client/internal/parse_test.go

PR adds `DAPR_GRPC_ENPOINT` environment variable support to client.
Address parser respects http[s] schemes, and TLS query options, as per [0008-S-sidecar-endpoint-tls.md](https://github.com/dapr/proposals/blob/main/0008-S-sidecar-endpoint-tls.md).
`DAPR_GRPC_ENDPONT` takes precedence over `DAPR_GRPC_PORT`.

Adds `DAPR_GRPC_ENPOINT` support to client

---

examples/configuration/README.md
examples/configuration/main.go

Eliminated ```time.sleep``` with ```sync.WaitGroup``` so ```SubscribeConfigurationItems``` can take proper time to finish and also updated to more appropriate logs

perf: enhanced configuration example

---

client/state.go
client/state_test.go

Fixes StateConsistency type to match protobufs, at the moment returns undefined for everything due to the logic.
https://github.com/dapr/dapr/blob/ed3417223c5ea4654f38df1fc5abee93e52cea6e/dapr/proto/common/v1/common.proto#L140

fix: update StateConsistency type to match protobufs

---

daprdocs/content/en/go-sdk-docs/go-client/_index.md
examples/crypto/README.md
examples/crypto/components/local-storage.yaml
examples/crypto/main.go

Taking direct reference from ```https://github.com/dapr/quickstarts/tree/master/cryptography/go/sdk```
The reason to add it here is to make sure our linter detects if any buggy changes happening to crypto code
Please reference the issue this PR will close: #395 

Examples: Added Crypto

---

.github/workflows/validate_examples.yaml
examples/grpc-service/README.md

This PR introduces an improved github action workflow for validating the examples.
Changes:
- Removes the hard-coded commit reference for the runtime.
- Implement events triggering a test with a custom ref for runtime/cli
- Split examples into singular jobs
-  Allows testing all examples even with individual failures
-  The log outputs are now split by example
- Bumps all actions to the latest versions.
- Use the repo `go.mod` as a source for the go version.
- Adds the socket example to the validation list
The validation run time has been decreased from 4 minutes to 2 minutes when using the latest release of the cli and daprd. This should remain fairly consistent with subsequent examples running in parallel with each other.
Old run: …

fix: Overhaul the validation action

---

client/client.go

The following allows the user of the SDK to customize the global logger, as it might break some application logging format. This way one can streamline all the program logging output.

allow to customize the default logger

---

.github/holopin.yml

The `yaml` file to award contribution badges has been updated such that each contributor can be awarded an SDK badge for their contribution to this repo.
This PR fixes #546 
Please make sure you've  completed the relevant tasks for this PR, out of the following list:

Update holopin.yml to award SDK badge to contributors 

---

workflow/client.go
workflow/client_test.go

Make workflow client struct public, so it can be referenced and typed and passed as a variable in other applications.

make workflow client struct public

---

client/scheduling.go

This fix stops the schedule field from being initialised unless otherwise explicitly with a value.
Please reference the issue this PR will close: #_N/A_

fix: stop schedule field from always being initialised

---

.github/workflows/validate_examples.yaml
examples/go.mod
examples/go.sum
go.mod
go.sum

Updates the workflow to use rc.8 of the cli and runtime. Also bumps the dapr/dapr import,  this should not require an RC as there have been no material changes to the protos.

chore: bump dapr & cli to rc.8 to test

---

service/http/topic.go

Made the writeHeader calls non superfluous.
https://github.com/dapr/go-sdk/issues/618
Please reference the issue this PR will close: #618

Fixed superfluous bug

---

workflow/client.go
workflow/client_test.go
workflow/state.go

Implements the missing bits to support workflows reuse id policy
Please reference the issue this PR will close: #493

workflows support reuse id policy

---

client/client.go

adds comments for https://github.com/dapr/go-sdk/issues/634

add deprecation comments

---

daprdocs/content/en/go-sdk-docs/go-service/grpc-service.md
daprdocs/content/en/go-sdk-docs/go-service/http-service.md
service/common/service.go
service/grpc/topic.go
service/http/topic.go
service/internal/topicregistrar.go
service/internal/topicregistrar_test.go

I introduced the `TopicEventSubscriber` interface and added an `AddTopicEventSubscriber` method to the `Server` interface. `TopicEventSubscriber` will allow more complex subscribers to be registered that are using structs so that dependencies like `sql.DB` objects or other parameters can be provided to subscribers and used to process incoming events.
I modified `TopicRegistrar` to register and store `TopicEventSubscriber` instead of `TopicEventHandler` in the `TopicRegistration struct. I created an adapter for `TopicEventHandler` so that it implements the new `TopicEventSubscriber` interface and can continue to be used without modification.
* I introduced the `TopicEventSubscriber` type instead of rewriting the `TopicEventHandler` type to not break existing code. I used the pattern that …

Introduce interface for topic event subscriber

---

daprdocs/content/en/go-sdk-docs/go-client/_index.md

client doc was missing a workflow example
Please reference the issue this PR will close: dapr/docs#3870

[docs] Add workflow to the client examples doc

---

.github/workflows/validate_examples.yaml
examples/actor/README.md
examples/actor/serving/main.go
examples/service/client/main.go
examples/service/config/binding.yaml

* Bumps the runtime version used in the example validation to 1.15.0-rc.2
* Fixes the service invocation (and bindings) example which used a deprecated endpoint to test a binding invocation.
* Fixes the actor example

chore: bump validation dapr runtime to 1.15.0-rc.2

---

client/subscribe.go

Same idea as python-sdk here: https://github.com/dapr/python-sdk/pull/783/files
When grpc code is unknown/unavailable, try to reconnect.

feat: reconnect stream when grpc code is unknown / unavailable

---

daprdocs/content/en/go-sdk-docs/go-client/_index.md

docs(sdk): add basic workflow example
