dapr/go-sdk

Readme.md

Adds few tags in readme to provide visibility into the state of the repo

test, release, go tags in readme

---

Makefile
Readme.md
example/Readme.md

[Link to the issue](https://github.com/dapr/go-sdk/issues/40).

Replace deprecated annotations

---

service/http/binding_test.go
service/http/invoke_test.go
service/http/service.go
service/http/service_test.go
service/http/topic_test.go

Implements new service creation with existing http mux #51

new service with existing http mux

---

Readme.md
service/Readme.md
service/grpc/Readme.md
service/http/Readme.md

Small example updates in Readme for API and callback service client

readme examples, templates

---

Readme.md

Corrects the updated name for GetBulkItems method on state

updated docs for GetBulkItems

---

example/pubsub/README.md
example/pubsub/config/pubsub.yaml
example/pubsub/pub.go
example/pubsub/sub.go

#38  I have written examples of pubsub, and I hope such simple examples will help.

pubsub sample

---

Readme.md

Correct some readme doc error by context.

Update README Doc

---

Readme.md
client/binding.go
client/client.go
client/client_test.go
client/invoke.go
client/pubsub.go
client/secret.go
client/state.go

Adds explicit Dapr API authentication token support defined in #28

explicit Dapr API authentication token support

---

.github/dependabot.yml

Doesn't seem to be supported in v2

removed default reviews

---

client/client.go
client/state.go
client/state_test.go

Add meta support in state delete api.
See issue #81

add meta in state delete api

---

Makefile

bump to v0.11

---

service/Readme.md

Updates template links to the new location

template link updates

---

Readme.md

Just a couple of minor grammatical changes I noticed whilst reading the read me.

Minor grammatical fixes

---

Makefile

v0.11.1 Version bump

---

service/http/binding_test.go
service/http/invoke_test.go
service/http/service.go
service/http/service_test.go
service/http/topic_test.go

Adds HTTP serving tests

---

service/grpc/binding.go
service/grpc/invoke.go
service/grpc/topic.go
service/http/binding.go
service/http/binding_test.go
service/http/invoke.go
service/http/invoke_test.go
service/http/topic.go
service/http/topic_test.go

handler checks addressing issue #100

---

Makefile

v1.0.0-rc-1

---

.gitignore
client/invoke.go
client/invoke_test.go

support set querystring when invoke

feat: Invoke will extract querystring from method

---

client/client.go
client/client_test.go
client/state.go
client/state_test.go

The related issue :
https://github.com/dapr/dapr/issues/2658

Add bulk delete state method in client sdk

---

client/invoke.go

fix function comments

---

daprdocs/README.md
daprdocs/content/en/go-sdk-contributing/go-contributing.md
daprdocs/content/en/go-sdk-docs/_index.md
daprdocs/content/en/go-sdk-docs/go-client/_index.md
daprdocs/content/en/go-sdk-docs/go-server/_index.md
daprdocs/content/en/go-sdk-docs/go-server/grpc-service.md
daprdocs/content/en/go-sdk-docs/go-server/http-service.md

Add markdown files to add Go SDK to Dapr docs

Add Dapr Docs for Go SDK

---

client/client.go
client/client_test.go
client/state.go
client/state_test.go

Adding support for state query API.
Resolves issue #215

add support for state query API

---

client/client.go
service/common/service.go
service/grpc/invoke.go
service/grpc/invoke_test.go
service/grpc/service.go
service/http/invoke.go
service/http/invoke_test.go
service/http/service.go

Signed-off-by: 1046102779 <seachen@tencent.com>

bugfix/apptoken: missing app token verification codes

---

.github/workflows/release-on-tag.yaml

Signed-off-by: yaron2 <schneider.yaron@live.com>

disable linter for release-on-tag

---

client/actor.go
client/actor_test.go
client/client.go
client/client_test.go

Follow  https://github.com/dapr/dapr/pull/4101
Issues：https://github.com/dapr/dapr/issues/3273

Support rename reminder

---

actor/manager/manager.go
actor/manager/manager_test.go
actor/mock/mock_manager.go
actor/runtime/actor_runtime.go
actor/runtime/actor_runtime_test.go
client/actor.go

As much as I like the idea of a Detective Actor 🕵️ - I'm think this should be `DeactiveActor`.

Fix misspelt activateActor name

---

Readme.md

Signed-off-by: Josh Dando <joshdando@Joshs-MacBook-Pro.local>

chore: fix some spelling mistakes in the readme

---

service/internal/topicregistrar.go
service/internal/topicregistrar_test.go

Signed-off-by: Paul Thiele <thielepaul@gmail.com>
Closes: #256

set subscription metadata in topicregistrar (fix #256)

---

.github/workflows/fossa.yml
Readme.md

Signed-off-by: Shubham Sharma <shubhash@microsoft.com>
This PR adds a CI step to ensure that dependencies with bad licenses are not introduced, along with a README badge.
Please reference the issue this PR will close: https://github.com/dapr/dapr/issues/4158

Add FOSSA workflow

---

client/state_test.go

update query test

---

client/configuration.go

Signed-off-by: 1046102779 <seachen@tencent.com>

fix(typo): client configuration subscribe

---

client/client.go
client/state.go

Signed-off-by: 1046102779 <seachen@tencent.com>

fix/typo: modify state  annotation

---

Readme.md
client/lock.go
client/lock_test.go

Signed-off-by: yaron2 <schneider.yaron@live.com>

change ownerID to lockOwner

---

actor/state/state_async_provider.go

…y or unmarshal fail
#326 
Signed-off-by: wangxw <996268132@qq.com>

fix #326 Differentiating between actor state key not found vs. unexpected error

---

.github/workflows/release-on-tag.yaml

Signed-off-by: Roberto J Rojas <robertojrojas@gmail.com>
(cherry picked from commit 3f795a2171ae2e688f358e405d2bc61d3cfa8709)

Fixes SDK_VERSION workflow check condition (#369)

---

client/client.go
client/client_test.go
client/configuration.go
client/configuration_test.go
examples/configuration/main.go

Update config subscribe method

---

.github/workflows/validate_examples.yaml
examples/configuration/README.md

Fixes https://github.com/dapr/go-sdk/issues/397

Fix env variable GOVER to "1.20" in validate_examples.yaml

---

client/actor.go
client/actor_test.go
client/client.go
client/client_test.go
go.mod
go.sum

Remove deprecated method RenameActorReminder

---

Readme.md
daprdocs/content/en/go-sdk-docs/go-client/_index.md

Depends on/is relevant for https://github.com/dapr/dapr/pull/7257

Docs for error handling

---

daprdocs/content/en/go-sdk-docs/go-client/_index.md

Small docs header update to bump the header level to correct visibility in the building blocks list
Please reference the issue this PR will close: N/A

docs: fix authentication header level

---

go.mod
go.sum

Dependency update for v1.13 stable github.com/dapr/dapr.

[1.13] update dapr/dapr dep

---

.github/workflows/validate_examples.yaml
examples/crypto/README.md

Fixes the mechanical markdown for the crypto example and adds the example to the validation workflow.
https://github.com/dapr/dapr/pull/7650#issuecomment-2021354475 Issue discovered when updating the runtime SDK validation workflow.
Please reference the issue this PR will close: #540

fix: add crypto validation example and fix mechanical markdown

---

actor/manager/manager.go

When checking for valid Actor methods, the SDK no longer emits warnings about invalid or inappropriate method signatures for the ones needed to be implemented for each Actor type.
Fixes #585

removed unnecessary warnings from actor reflection

---

examples/actor/README.md
examples/configuration/README.md
examples/grpc-service/README.md
examples/hello-world/README.md
examples/pubsub/README.md
examples/service/README.md
examples/socket/README.md
examples/workflow-parallel/README.md
examples/workflow/README.md

Remove the flaky/ineffective 'stop' steps in the validation process
Ensures there are appropriate timeouts added to each step
Please reference the issue this PR will close: #_N/A_

chore: remove dapr stop steps and add appropriate timeouts

---

.github/workflows/test-on-push.yaml

Removes the extraneous test versions

ci: only test using go.mod version

---

go.mod
go.sum
workflow/client.go
workflow/context.go
workflow/state.go
workflow/state_test.go
workflow/workflow.go
workflow/workflow_test.go

Updates dapr/durabletask-go to match the version used in dapr/dapr latest 1.15 rc

update durabletask ref

---

workflow/worker.go

Adding the name of the failing activity. For more detail

Adding the name of the failing activity. For more detail

---

service/common/type.go
service/grpc/topic.go
service/internal/topicregistrar.go
service/internal/topicsubscription.go
service/internal/topicsubscription_test.go

Adds missing deadletter topic support for non-streaming subscriptions.

add deadlettertopic support to non-streaming subscriptions

---

client/conversation.go
examples/conversation/main.go
examples/go.mod
examples/go.sum
go.mod
go.sum

Updates according to https://github.com/dapr/dapr/pull/8510

Update conversation api field name

---

.github/workflows/validate_examples.yaml

ci: revert rc tests

---

client/jobs.go

- Introduces overwrite field to jobs
- Fix tests due to new proto fields

chore: Add overwrite field to job request
